import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import ts from 'typescript';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import type { Flow } from '../src/skills/flow.js';
import { SkillStore, type Skill, type SkillStep } from '../src/skills/store.js';
import { emitFlowFile, emitSpecFile } from '../src/spec/emit.js';
import { flowToSpec, type SpecFlow, type SpecSegment, type SpecStep } from '../src/spec/ir.js';
import { compileFlow } from '../src/spec/index.js';

const FWAT2 = path.resolve('bench/results-published/fwat2-skills');
const RDFLOW = path.resolve('bench/results-published/flows/rdflow.json');

/**
 * The emitted file must be real TypeScript, not text that looks like it: a
 * generated spec that does not parse is the one failure mode a reviewer
 * cannot work around. transpileModule reports syntax diagnostics only, which
 * is exactly the question here — the file is compiled by the user's own
 * project, with their own @playwright/test types.
 */
function syntaxErrors(source: string, fileName = 'flow.ts'): string[] {
  const out = ts.transpileModule(source, {
    fileName,
    reportDiagnostics: true,
    compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext },
  });
  return (out.diagnostics ?? []).map((d) => ts.flattenDiagnosticMessageText(d.messageText, ' '));
}

type Stub = { count: () => Promise<number> };

/** A Locator stub whose count() answers from `next`, one call at a time. */
function locatorStub(next: () => number): Stub {
  return { count: async () => next() };
}

/** A Page stub for the inlined `pick`: it only ever waits. */
function pageStub(): { waitForTimeout: (ms: number) => Promise<void> } {
  return { waitForTimeout: async () => {} };
}

/**
 * The `pick` helper cut out of an emitted file and made callable, so its
 * BEHAVIOUR can be tested rather than its text. Only the final brace of the
 * function sits at column 0, which is what bounds the cut.
 */
function runnablePick(source: string): {
  pick: (page: unknown, candidates: Stub[], where: string, opts?: { any?: boolean }) => Promise<Stub>;
  drift: string[];
} {
  const consts = /const PICK_WAIT_MS = \d+;\nconst PICK_POLL_MS = \d+;/.exec(source);
  const fn = /\nasync function pick\(page: Page[\s\S]*?\n\}\n/.exec(source);
  if (!consts || !fn) throw new Error('pick helper not found in the emitted source');
  const js = ts.transpileModule(`${consts[0]}\n${fn[0]}`, {
    compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext },
  }).outputText;
  const drift: string[] = [];
  const build = new Function('DRIFT', 'console', `${js}\nreturn pick;`) as (
    d: string[],
    c: unknown,
  ) => (page: unknown, candidates: Stub[], where: string, opts?: { any?: boolean }) => Promise<Stub>;
  return { pick: build(drift, { warn: () => {} }), drift };
}

/** The FLOW constant as LIFT will read it back. */
function flowConstant(source: string): unknown {
  const body = /\/\/ @sitelooper-flow-begin\n([\s\S]*?)\n\/\/ @sitelooper-flow-end/.exec(source);
  if (!body) throw new Error('markers missing');
  return JSON.parse(body[1].replace(/^export const FLOW = /, '').replace(/;$/, ''));
}

function segment(steps: SkillStep[], over: Partial<SpecSegment> = {}): SpecSegment {
  return {
    id: 's_test1',
    template: 'do the thing with {{v1}}',
    params: { v1: { example: 'Widget A', usedIn: [1], known: true } },
    preconditions: { urlPattern: 'http://app.test/items' },
    steps,
    ...over,
  };
}

function specOf(steps: SkillStep[], over: Partial<SpecStep> = {}, flowOver: Partial<SpecFlow> = {}): SpecFlow {
  const step: SpecStep = {
    id: '01-do',
    instruction: 'do the thing',
    params: { v1: '{{name}}' },
    outputs: [],
    segments: [segment(steps)],
    ...over,
  };
  return { version: 1, name: 'demo', origin: 'http://app.test', startUrl: 'http://app.test/', vars: ['name'], steps: [step], ...flowOver };
}

const emit = (spec: SpecFlow) => emitFlowFile(spec, { tier: 'plain' }).source;

describe('emitFlowFile layout', () => {
  const source = emit(specOf([{ tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'role', role: 'button', name: 'Save' }] } }]));

  it('opens with the version marker and the do-not-edit header', () => {
    const head = source.split('\n');
    expect(head[0]).toBe('// @sitelooper-flow v1');
    expect(head[1]).toContain('Generated by sitelooper from flow "demo"');
    expect(head[3]).toBe("import { expect, type Page } from '@playwright/test';");
  });

  it('carries the spec verbatim between the lift markers', () => {
    const spec = specOf([{ tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'role', role: 'button', name: 'Save' }] } }]);
    expect(emit(spec)).toContain(`export const FLOW = ${JSON.stringify(spec, null, 2)};`);
    expect(flowConstant(emit(spec))).toEqual(JSON.parse(JSON.stringify(spec)));
  });

  it('declares Vars, Outputs, the steps object and runFlow', () => {
    expect(source).toContain('export type Vars = { name: string };');
    expect(source).toContain('export interface Outputs {');
    expect(source).toContain("  async '01-do'(page: Page, p: { v1: string }, outputs: Outputs): Promise<void> {");
    expect(source).toContain('export async function runFlow(page: Page, vars: Vars): Promise<Outputs> {');
    expect(source).toContain("  await page.goto('http://app.test/');");
    expect(source).toContain("  await steps['01-do'](page, { v1: vars.name }, outputs);");
    expect(syntaxErrors(source)).toEqual([]);
  });

  // DRIFT is exported unconditionally, not only when `pick` is emitted: a
  // caller's `.spec.ts` imports it once, statically, and a flow that has no
  // multi-candidate step TODAY may gain one the moment `repair` widens a
  // chain — the import in the user's own, never-rewritten file must not have
  // to change to keep compiling. The array is simply empty until a `pick`
  // call actually falls through.
  it('exports DRIFT even when the flow has no step that needs pick', () => {
    expect(source).not.toContain('async function pick');
    expect(source).toContain('export const DRIFT: string[] = [];');
  });

  it('types p as an open record when the step has no slots', () => {
    const spec = specOf([{ tool: 'back', args: {}, locators: {} }], { params: {}, segments: [segment([{ tool: 'back', args: {}, locators: {} }], { params: {} })] });
    expect(emit(spec)).toContain("async '01-do'(page: Page, p: Record<string, string>, outputs: Outputs)");
  });
});

describe('step bodies', () => {
  const one = (step: SkillStep, over?: Partial<SpecSegment>) =>
    emit(specOf([step], over ? { segments: [segment([step], over)] } : {}));

  it('renders each tool with its Playwright statement', () => {
    const loc = { target: [{ kind: 'testid' as const, attr: 'data-testid', value: 'save' }] };
    expect(one({ tool: 'click', args: { target: '@e1' }, locators: loc })).toContain("await page.getByTestId('save').click();");
    expect(one({ tool: 'dblclick', args: { target: '@e1' }, locators: loc })).toContain(".dblclick();");
    expect(one({ tool: 'right_click', args: { target: '@e1' }, locators: loc })).toContain(".click({ button: 'right' });");
    expect(one({ tool: 'fill', args: { target: '@e1', value: '{{v1}}' }, locators: loc })).toContain('.fill(`${p.v1}`);');
    expect(one({ tool: 'type', args: { target: '@e1', text: 'abc', delay_ms: 50 }, locators: loc })).toContain(".pressSequentially('abc', { delay: 50 });");
    expect(one({ tool: 'press', args: { target: '@e1', key: 'Enter' }, locators: loc })).toContain(".press('Enter');");
    expect(one({ tool: 'select', args: { target: '@e1', option: 'Client One' }, locators: loc })).toContain(".selectOption({ label: 'Client One' });");
    expect(one({ tool: 'check', args: { target: '@e1', checked: true }, locators: loc })).toContain('.check();');
    expect(one({ tool: 'check', args: { target: '@e1', checked: false }, locators: loc })).toContain('.uncheck();');
    expect(one({ tool: 'goto', args: { url: 'http://app.test/x' }, locators: {} })).toContain("await page.goto('http://app.test/x');");
  });

  it('presses a key on the page when the recording had no target', () => {
    expect(one({ tool: 'press', args: { key: 'Escape' }, locators: {} })).toContain("await page.keyboard.press('Escape');");
  });

  it('arms a dialog handler before the click that raises it', () => {
    expect(one({ tool: 'dialog_expect', args: { action: 'accept' }, locators: {} })).toContain("page.once('dialog', (dialog) => dialog.accept());");
    expect(one({ tool: 'dialog_expect', args: { action: 'dismiss', count: 2 }, locators: {} })).toContain("page.on('dialog', (dialog) => dialog.dismiss());");
  });

  it('writes a labelled read into outputs, by kind', () => {
    const loc = { target: [{ kind: 'id' as const, selector: '#total' }] };
    expect(one({ tool: 'read', args: { target: '@e1', what: 'text' }, locators: loc, label: 'total' })).toContain(
      "outputs['01-do.total'] = (await page.locator('#total').textContent()) ?? '';",
    );
    expect(one({ tool: 'read', args: { target: '@e1', what: 'value' }, locators: loc, label: 'name' })).toContain(
      "outputs['01-do.name'] = await page.locator('#total').inputValue();",
    );
    expect(one({ tool: 'read', args: { what: 'url' }, locators: {}, label: 'here' })).toContain("outputs['01-do.here'] = page.url();");
    expect(one({ tool: 'read_all', args: { target: '@e1', what: 'text' }, locators: loc, label: 'rows' })).toContain('.allTextContents()).join(');
  });

  it('leaves an unlabelled read as an observation', () => {
    const out = one({ tool: 'read', args: { target: '@e1', what: 'text' }, locators: { target: [{ kind: 'id', selector: '#t' }] } });
    expect(out).toContain('// observed: read text (unlabelled');
    expect(out).not.toContain('outputs[');
  });

  it('resolves a multi-candidate action through pick, never through a .or() union', () => {
    const out = one({
      tool: 'fill',
      args: { target: '@e1', value: 'x' },
      locators: {
        target: [
          { kind: 'id', selector: '#login-email' },
          { kind: 'css', selector: '[data-testid="form-dialog"] input' },
        ],
      },
    });
    expect(out).toContain('const el1 = await pick(page, [');
    expect(out).toContain("  page.locator('#login-email'),");
    expect(out).toContain('await el1.fill(');
    // a union would be a strict-mode violation the moment a fallback matched two inputs
    expect(out).not.toContain('.or(page');
    expect(out).toContain('async function pick(page: Page, candidates: Locator[]');
    expect(out).toContain("import { expect, type Locator, type Page } from '@playwright/test';");
  });

  it('reports a fallthrough as one stable, grep-able drift line and pushes it into DRIFT', () => {
    const out = one({
      tool: 'fill',
      args: { target: '@e1', value: 'x' },
      locators: {
        target: [
          { kind: 'id', selector: '#login-email' },
          { kind: 'css', selector: '[data-testid="form-dialog"] input' },
        ],
      },
    });
    expect(out).toContain("const el1 = await pick(page, [");
    expect(out).toContain("  page.locator('#login-email'),");
    expect(out).toContain("  page.locator('[data-testid=\"form-dialog\"] input'),");
    expect(out).toContain("], '01-do s_test1/1 target');");
    expect(out).toContain('if (won > 0) {');
    expect(out).toContain(
      "const line = `[sitelooper drift] ${where}: primary ${String(candidates[0])} missed; used #${won + 1} ${String(candidates[won])}`;",
    );
    expect(out).toContain('console.warn(line);');
    expect(out).toContain('DRIFT.push(line);');
    expect(syntaxErrors(out)).toEqual([]);
  });

  /**
   * fwrd42, `sitelooper repair` had promoted
   * `page.locator('tr', { hasText: '{{v5}}' }).locator('td:nth-of-type(1)')` to
   * primary off live replay evidence, yet the compiled spec logged it as missed
   * on ~40% of runs and took `getByText` (twice a purely structural fallback)
   * instead. Not ambiguity and not hasText semantics: the repair-desk bench
   * defers its parts refetch ~500ms BY DESIGN, landing on a poll boundary, and
   * a pass of `pick` is not one instant — every count() is its own round trip.
   * Measured, the scoped primary counted 0 at t, getByText counted 1 at t+3ms,
   * and the primary counted 1 again 3ms after that.
   */
  describe('pick re-checks the candidates ahead before demoting the primary', () => {
    const scopedChain: SkillStep = {
      tool: 'wait_for',
      args: { target: '@e1', state: 'visible' },
      locators: {
        target: [
          { kind: 'scoped', container: 'tr', hasText: '{{v1}}', selector: 'td:nth-of-type(1)' },
          { kind: 'text', text: '{{v1}}' },
        ],
      },
    };

    it('emits the scoped primary ahead of the text fallback', () => {
      const out = one(scopedChain);
      expect(out).toContain("  page.locator('tr', { hasText: `${p.v1}` }).locator('td:nth-of-type(1)'),");
      expect(out).toContain('  page.getByText(`${p.v1}`, { exact: true }),');
      expect(syntaxErrors(out)).toEqual([]);
    });

    it('keeps the primary when it only missed because the row painted mid-pass', async () => {
      const { pick, drift } = runnablePick(one(scopedChain));
      // The primary is sampled first in every pass, so it is the candidate a
      // paint at the poll boundary makes look absent. It is there 3ms later.
      let samples = 0;
      const primary = locatorStub(() => (++samples === 1 ? 0 : 1));
      const fallback = locatorStub(() => 1);
      expect(await pick(pageStub(), [primary, fallback], 'w')).toBe(primary);
      expect(drift).toEqual([]);
    });

    it('still falls through, and still reports drift, when the primary is really gone', async () => {
      const { pick, drift } = runnablePick(one(scopedChain));
      const primary = locatorStub(() => 0);
      const fallback = locatorStub(() => 1);
      expect(await pick(pageStub(), [primary, fallback], '01-do s_test1/1 target')).toBe(fallback);
      expect(drift).toHaveLength(1);
      expect(drift[0]).toContain('[sitelooper drift] 01-do s_test1/1 target: primary');
      expect(drift[0]).toContain('used #2');
    });

    it('does not let the re-check hand back a candidate that is ambiguous', async () => {
      const { pick, drift } = runnablePick(one(scopedChain));
      // Two rows carry the text: replay skips a candidate that is not unique
      // and so must the spec — the re-check is about WHEN a candidate is
      // sampled, never about relaxing what counts as resolved.
      const primary = locatorStub(() => 2);
      const fallback = locatorStub(() => 1);
      expect(await pick(pageStub(), [primary, fallback], 'w')).toBe(fallback);
      expect(drift).toHaveLength(1);
    });
  });

  it('places a @step location comment before each step\'s first statement, in order', () => {
    const stepA: SkillStep = { tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'id', selector: '#a' }] } };
    const stepB: SkillStep = { tool: 'click', args: { target: '@e2' }, locators: { target: [{ kind: 'id', selector: '#b' }] } };
    const out = emit(specOf([stepA, stepB]));
    const lines = out.split('\n');
    const stepLines = lines.map((l) => l.trim()).filter((l) => l.startsWith('// @step '));
    expect(stepLines).toEqual(['// @step 01-do s_test1/1', '// @step 01-do s_test1/2']);
    // each @step comment is the line immediately above its own statement
    const i1 = lines.findIndex((l) => l.trim() === '// @step 01-do s_test1/1');
    expect(lines[i1 + 1]).toContain("page.locator('#a').click();");
    const i2 = lines.findIndex((l) => l.trim() === '// @step 01-do s_test1/2');
    expect(lines[i2 + 1]).toContain("page.locator('#b').click();");
  });

  it('drops a duplicate candidate expression rather than resolving it twice', () => {
    const out = one({
      tool: 'click',
      args: { target: '@e1' },
      locators: { target: [{ kind: 'id', selector: '#go' }, { kind: 'css', selector: '#go' }] },
    });
    expect(out).toContain("await page.locator('#go').click();");
    expect(out).not.toContain('pick(page');
  });

  it('inlines the pick helper only when a step needs it', () => {
    const out = one({ tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'id', selector: '#b' }] } });
    expect(out).not.toContain('async function pick');
    expect(out).toContain("import { expect, type Page } from '@playwright/test';");
  });

  it('lets a read_all match many, which is what it is for', () => {
    const out = one({
      tool: 'read_all',
      args: { target: '@e1', what: 'text' },
      locators: { target: [{ kind: 'id', selector: '#rows' }, { kind: 'css', selector: '.row' }] },
      label: 'rows',
    });
    expect(out).toMatch(/], '[^']+', \{ any: true \}\);/);
  });

  it('names what Tier 2 loses when a point candidate is dropped', () => {
    const out = one({
      tool: 'click',
      args: { target: '@e1' },
      locators: { target: [{ kind: 'role', role: 'button', name: 'Save' }, { kind: 'point', x: 10, y: 20, w: 5, h: 5, role: 'button', tag: 'button', vw: 800, vh: 600 }] },
    });
    expect(out).toContain('// TODO: dropped the recorded position fallback (button at 10,20)');
  });

  it('falls back to a TODO when no candidate can be expressed', () => {
    const spec = specOf([{ tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'point', x: 1, y: 2, w: 3, h: 4, role: null, tag: 'div', vw: 800, vh: 600 }] } }]);
    const { source, warnings } = emitFlowFile(spec, { tier: 'plain' });
    expect(source).toContain('// TODO: no locator this compiler can express for click');
    expect(warnings.some((w) => w.includes('no locator a spec can express'))).toBe(true);
  });
});

describe('expectations', () => {
  const withExpect = (expectation: SkillStep['expect'], tool = 'click', args: Record<string, unknown> = { target: '@e1' }) =>
    emit(specOf([{ tool, args, locators: { target: [{ kind: 'id', selector: '#b' }] }, expect: expectation }]));

  it('turns a url pattern into an anchored regex, ids wildcarded and slots escaped', () => {
    expect(withExpect({ urlPattern: 'http://app.test/items/:id' })).toContain(
      'await expect(page).toHaveURL(new RegExp(`^http://app\\\\.test/items/[^/]+(?:[?#].*)?$`));',
    );
    expect(withExpect({ urlPattern: 'http://app.test/items/{{v1}}' })).toContain('${escapeRe(p.v1)}');
    // the query is not part of a page's identity; the hash route is
    expect(withExpect({ urlPattern: 'http://app.test/a?q=1#/detail' })).toContain('(?:\\\\?[^#]*)?#/detail$');
  });

  it('inlines escapeRe only when a body uses it', () => {
    expect(withExpect({ urlPattern: 'http://app.test/items/{{v1}}' })).toContain('function escapeRe(s: string): string {');
    expect(withExpect({ urlPattern: 'http://app.test/items/:id' })).not.toContain('function escapeRe');
  });

  it('groups the recorded lines into one any-of assertion per group, as the effect gate has them', () => {
    const out = withExpect({
      addedContains: ['- heading "{{v1}} Widget"', '- status "Loading…"', '- generic "sidebar"', '- tab "New Project"'],
    });
    // the parameterised group is its own assertion: those lines are the hard gate
    expect(out).toContain("await expect(page.getByRole('heading', { name: `${p.v1} Widget`, exact: false }).first()).toBeVisible();");
    // the plain lines are ONE union, not one assertion each — replay stops only when none of them shows
    expect(out).toContain("await expect(page.getByRole('generic', { name: 'sidebar', exact: false })");
    expect(out).toContain(".or(page.getByRole('tab', { name: 'New Project', exact: false }))");
    expect(out.split('\n').filter((l) => l.includes('toBeVisible')).length).toBe(2);
    // a transient line never becomes an assertion (the FLOW constant still records it)
    expect(out).not.toContain("getByRole('status'");
  });

  it('names the presence check loosely, because a recorded line is not a Playwright name', () => {
    expect(withExpect({ addedContains: ['- menu "View Details Remove"'] })).toContain(
      "await expect(page.getByRole('menu', { name: 'View Details Remove', exact: false }).first()).toBeVisible();",
    );
  });

  it('drops a fill echo in favour of the consequential change', () => {
    const out = withExpect({ addedContains: ['- textbox "": {{v1}}', '- heading "{{v1}}"'] }, 'fill', { target: '@e1', value: '{{v1}}' });
    expect(out).toContain("page.getByRole('heading'");
    expect(out).not.toContain('- textbox ""');
  });

  it('keeps a lone echo as an observation rather than inventing a locator', () => {
    const out = withExpect({ addedContains: ['- textbox "": {{v1}}'] }, 'fill', { target: '@e1', value: '{{v1}}' });
    expect(out).toContain('// observed (nothing nameable in it): - textbox "": {{v1}}');
    expect(out).not.toContain('toBeVisible');
  });

  it('asserts a url only where the pattern changes', () => {
    const at = (pattern: string): SkillStep => ({
      tool: 'click',
      args: { target: '@e1' },
      locators: { target: [{ kind: 'id', selector: '#b' }] },
      expect: { urlPattern: pattern },
    });
    const source = emit(specOf([at('http://app.test/a'), at('http://app.test/a'), at('http://app.test/b')]));
    const asserted = source.split('\n').filter((l) => l.includes('toHaveURL'));
    expect(asserted.length).toBe(2);
    expect(asserted[1]).toContain('/b');
  });

  it('leaves an alert as a comment — a toast is volatile', () => {
    expect(withExpect({ alertContains: 'Saved 3 items' })).toContain('// expected alert containing "Saved 3 items"');
  });
});

describe('preconditions, minting and loops', () => {
  it('checks a bound identity marker at segment entry and skips an unbound one', () => {
    const step: SkillStep = { tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'id', selector: '#b' }] } };
    const bound = emit(specOf([step], { segments: [segment([step], { preconditions: { urlPattern: 'http://app.test/x', requireText: ['{{v1}}'] } })] }));
    expect(bound).toContain('await expect(page.getByText(`${p.v1}`).first()).toBeVisible();');
    const unbound = emit(
      specOf([step], { segments: [segment([step], { params: {}, preconditions: { urlPattern: 'http://app.test/x', requireText: ['{{v9}}'] } })] }),
    );
    expect(unbound).toContain('is unbound here — nothing to check.');
  });

  it('comments the precondition url rather than asserting it', () => {
    const step: SkillStep = { tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'id', selector: '#b' }] } };
    expect(emit(specOf([step]))).toContain('// recorded on a page matching http://app.test/items');
  });

  it('binds a derived value off the live url after the step that mints it', () => {
    const step: SkillStep = { tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'id', selector: '#save' }] }, mints: { at: 'p1' } };
    const source = emit(specOf([step], { segments: [segment([step], { derived: { d1: { step: 1, at: 'p1', example: '42' } } })] }));
    expect(source).toContain("p.d1 = urlPart(page.url(), 'p1');");
    expect(source).toContain('function urlPart(url: string, label: string): string {');
    expect(source).toContain("// This step CREATES a record (its id is url part 'p1')");
    // a minted slot is declared on p and starts empty: only the live run can fill it
    expect(source).toContain("await steps['01-do'](page, { d1: '', v1: vars.name }, outputs);");
  });

  it('unrolls a folded loop as a capped for-loop on the first match', () => {
    const body: SkillStep[] = [{ tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'role', role: 'button', name: 'Remove' }] } }];
    const loop: SkillStep = { tool: 'loop', args: {}, locators: {}, body, while: [{ kind: 'role', role: 'button', name: 'Remove' }], max: 7 };
    const source = emit(specOf([loop]));
    expect(source).toContain("const guard1 = page.getByRole('button', { name: 'Remove', exact: true });");
    expect(source).toContain('for (let i = 0; i < 7 && (await guard1.count()) > 0; i++) {');
    expect(source).toContain(".first().click();");
    expect(source).not.toContain('.or(page');
    expect(source).toContain('// FIRST match');
    expect(syntaxErrors(source)).toEqual([]);
  });
});

describe('flow-level wiring', () => {
  it('threads vars, step outputs and env secrets into the call site', () => {
    const step: SkillStep = { tool: 'fill', args: { target: '@e1', value: '{{v1}}' }, locators: { target: [{ kind: 'id', selector: '#i' }] } };
    const spec = specOf([step], {
      params: { v1: '{{name}}', v2: '{{02-b.title}}', v3: 'literal-{{name}}', v4: '{{env:BENCH_PASSWORD}}' },
      segments: [
        segment([step], {
          params: {
            v1: { example: 'a', usedIn: [1] },
            v2: { example: 'b', usedIn: [1] },
            v3: { example: 'c', usedIn: [1] },
            v4: { example: 'd', usedIn: [1] },
          },
        }),
      ],
    });
    const source = emit(spec);
    expect(source).toContain("v1: vars.name");
    expect(source).toContain("v2: outputs['02-b.title'] ?? ''");
    expect(source).toContain('v3: `literal-${vars.name}`');
    expect(source).toContain("v4: process.env.BENCH_PASSWORD ?? ''");
    expect(syntaxErrors(source)).toEqual([]);
  });

  it('inlines a recorded value with a warning when the flow binds no slot', () => {
    const step: SkillStep = { tool: 'fill', args: { target: '@e1', value: '{{v1}}' }, locators: { target: [{ kind: 'id', selector: '#i' }] } };
    const { source, warnings } = emitFlowFile(specOf([step], { params: {} }), { tier: 'plain' });
    expect(source).toContain("v1: 'Widget A' /* recorded value; no flow binding */");
    expect(warnings).toContain('01-do: slot v1 has no flow binding — the recorded value is inlined');
  });

  it('throws in the body of a step with no converged procedure', () => {
    const spec = specOf([], { segments: [], instruction: 'archive the ticket' });
    const source = emit(spec);
    expect(source).toContain('// TODO: no converged procedure for "archive the ticket"');
    expect(source).toContain("throw new Error('step 01-do has no converged procedure");
    expect(syntaxErrors(source)).toEqual([]);
  });
});

describe('emitSpecFile', () => {
  it('is a thin user-owned scaffold that imports the generated half', () => {
    const source = emitSpecFile(specOf([{ tool: 'back', args: {}, locators: {} }]));
    expect(source).toContain("import { runFlow, steps, DRIFT } from './demo.flow';");
    expect(source).toContain("const outputs = await runFlow(page, { name: process.env.NAME ?? '' });");
    expect(source).toContain('sitelooper never rewrites it');
    expect(source).toContain("DRIFT.length");
    expect(syntaxErrors(source, 'demo.spec.ts')).toEqual([]);
  });
});

describe('the fwat2 store, every skill as a one-step flow', () => {
  const store = new SkillStore(FWAT2);
  const skills = store.all();

  it('has the store the rest of this suite compiles', () => {
    expect(skills.length).toBe(18);
  });

  for (const skill of skills) {
    it(`compiles ${skill.id} to a parsable spec`, () => {
      const flow: Flow = {
        name: `one-${skill.id}`,
        origin: skill.origin,
        startUrl: skill.origin + '/',
        vars: [],
        steps: [{ id: '01-do', instruction: skill.template, skill: skill.id, outputs: [], recorded: {} }],
        provenance: { session: 'test', created: new Date(0).toISOString() },
      };
      const { spec, warnings } = flowToSpec(flow, store);
      expect(spec.steps[0].segments.length).toBeGreaterThan(0);
      if (skill.status === 'demoted') expect(warnings.join(' ')).toContain('demoted');
      const { source } = emitFlowFile(spec, { tier: 'plain' });
      expect(syntaxErrors(source, `${skill.id}.flow.ts`)).toEqual([]);
      expect(flowConstant(source)).toEqual(JSON.parse(JSON.stringify(spec)));
      expect(syntaxErrors(emitSpecFile(spec), `${skill.id}.spec.ts`)).toEqual([]);
    });
  }

  it('follows a seq chain into every segment of the procedure', () => {
    const chained = skills.find((s: Skill) => s.seq)!;
    const flow: Flow = {
      name: 'chained',
      origin: chained.origin,
      startUrl: chained.origin + '/',
      vars: [],
      steps: [{ id: '01-open', instruction: chained.template, skill: chained.id, outputs: [], recorded: {} }],
      provenance: { session: 'test', created: new Date(0).toISOString() },
    };
    const { spec } = flowToSpec(flow, store);
    expect(spec.steps[0].segments.map((s) => s.id)).toEqual(
      skills.filter((s: Skill) => s.seq?.chain === chained.seq!.chain).sort((a, b) => a.seq!.index - b.seq!.index).map((s) => s.id),
    );
  });

  it('emits the real statements for the delete-and-archive skill', () => {
    const skill = store.get('s_f2ee63')!;
    const flow: Flow = {
      name: 'delete-both',
      origin: skill.origin,
      startUrl: skill.origin + '/project-manager',
      vars: ['runid'],
      steps: [{ id: '01-do', instruction: skill.template, skill: skill.id, params: { v1: '{{runid}}' }, outputs: [], recorded: {} }],
      provenance: { session: 'test', created: new Date(0).toISOString() },
    };
    const { source } = emitFlowFile(flowToSpec(flow, store).spec, { tier: 'plain' });
    // the identity-scoped primary, its hasText guard on the fallbacks, and the dialog arming
    expect(source).toContain("page.locator('div.data-list-row', { hasText: `${p.v2}` })");
    expect(source).toContain('.filter({ hasText: `${p.v2}` })');
    expect(source).toContain("page.once('dialog', (dialog) => dialog.accept());");
    expect(source).toContain('await expect(page).toHaveURL(new RegExp(`^http://localhost:5173/project-manager');
    expect(source).toContain("v1: vars.runid");
  });
});

describe('flowToSpec over a published flow', () => {
  it('reports every step of a flow whose skills are not in the store', () => {
    const flow = JSON.parse(fs.readFileSync(RDFLOW, 'utf8')) as Flow;
    const { spec, warnings } = flowToSpec(flow, new SkillStore(FWAT2));
    expect(spec.steps.map((s) => s.id)).toEqual(flow.steps.map((s) => s.id));
    expect(warnings.filter((w) => w.includes('no converged procedure')).length).toBe(flow.steps.length);
    const { source } = emitFlowFile(spec, { tier: 'plain' });
    expect(syntaxErrors(source, 'rdflow.flow.ts')).toEqual([]);
    expect((source.match(/has no converged procedure/g) ?? []).length).toBeGreaterThanOrEqual(flow.steps.length);
  });
});

describe('compileFlow', () => {
  let dir: string;
  beforeAll(() => {
    dir = fs.mkdtempSync(path.join(os.tmpdir(), 'sl-spec-'));
  });
  afterAll(() => fs.rmSync(dir, { recursive: true, force: true }));

  it('writes both files, then never rewrites the user-owned one', () => {
    const out = path.join(dir, 'out');
    const first = compileFlow(RDFLOW, { store: new SkillStore(FWAT2), outDir: out });
    expect(first.flowFile).toBe(path.join(out, 'rdflow.flow.ts'));
    expect(first.specFile).toBe(path.join(out, 'rdflow.spec.ts'));
    expect(first.compilable).toBe(false);

    fs.appendFileSync(first.specFile!, '\n// mine\n');
    const again = compileFlow(RDFLOW, { store: new SkillStore(FWAT2), outDir: out });
    expect(again.specFile).toBeNull();
    expect(fs.readFileSync(path.join(out, 'rdflow.spec.ts'), 'utf8')).toContain('// mine');
    // the generated half is regenerated every time
    expect(fs.readFileSync(again.flowFile, 'utf8')).toContain('// @sitelooper-flow v1');

    const forced = compileFlow(RDFLOW, { store: new SkillStore(FWAT2), outDir: out, force: true });
    expect(forced.specFile).not.toBeNull();
    expect(fs.readFileSync(path.join(out, 'rdflow.spec.ts'), 'utf8')).not.toContain('// mine');
  });

  it('refuses a flow it cannot find', () => {
    expect(() => compileFlow('no-such-flow', { outDir: dir })).toThrow(/no flow named/);
  });
});
